/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ap1;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Microsoft USer's
 */
public class LoginAnggota extends javax.swing.JFrame {
    int counter = 0;
    
    Connection conn;
    Statement stat;
    ResultSet rs;
    String sql;
    /**
     * Creates new form Login
     */
        public LoginAnggota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        showpass = new javax.swing.JCheckBox();
        btnloginadmin = new javax.swing.JButton();
        btncreateuser = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setBackground(new java.awt.Color(255, 102, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Login Anggota");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 60, 129, 22);

        jLabel2.setText("Username");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 90, 55, 16);
        jPanel1.add(username);
        username.setBounds(130, 90, 259, 22);

        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 130, 55, 16);
        jPanel1.add(password);
        password.setBounds(130, 130, 259, 22);

        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin);
        btnlogin.setBounds(130, 210, 259, 25);

        showpass.setText("Show Password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        jPanel1.add(showpass);
        showpass.setBounds(130, 160, 259, 25);

        btnloginadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/iconProfile.png"))); // NOI18N
        btnloginadmin.setText("Admin");
        btnloginadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginadminActionPerformed(evt);
            }
        });
        jPanel1.add(btnloginadmin);
        btnloginadmin.setBounds(430, 10, 85, 25);

        btncreateuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/iconProfile.png"))); // NOI18N
        btncreateuser.setText("Create User");
        btncreateuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateuserActionPerformed(evt);
            }
        });
        jPanel1.add(btncreateuser);
        btncreateuser.setBounds(330, 260, 117, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ap1/f4b4942c3d6c8e3b296da37e5e64521f 2.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 540, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        
        try {
            conn = koneksi.config();
            sql = "SELECT * FROM anggota WHERE kode_anggota='"+username.getText()+"' AND pass_anggota='"+password.getText()+"'";
            rs = stat.executeQuery(sql);
            if(rs.next()){
                if(username.getText().equals(rs.getString("username")) && password.getText().equals(rs.getString("password"))){
                    JOptionPane.showMessageDialog(null, "berhasil login");
                    new DashboardAnggota().show();
                    this.dispose();
                } else if (username.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Username Kosong");
                    username.requestFocus();
                } else if (password.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Password Kosong");
                    password.requestFocus();
                } 
            } else {
                    JOptionPane.showMessageDialog(null, "username atau password salah");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Login, mohon diulang ");
        }
        
//        if (username.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "Username Kosong");
//            username.requestFocus();
//        } else if (password.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "Password Kosong");
//            password.requestFocus();
//        } 
    }//GEN-LAST:event_btnloginActionPerformed

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
    if (showpass.isSelected()) {
            password.setEchoChar((char)0);
         }else{
            password.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassActionPerformed

    private void btnloginadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginadminActionPerformed
    new LoginAdmin().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnloginadminActionPerformed

    private void btncreateuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateuserActionPerformed
    new CreateUser().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btncreateuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAnggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreateuser;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnloginadmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
